<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>c5e5fac8-c258-44d9-bffd-23a1ea7f2c7d</UserSecretsId>
    <UseRazorSourceGenerator>true</UseRazorSourceGenerator>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="AIGreetingInstructions.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="AIGreetingInstructions.txt.old">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="AIInstructions.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Remove="AIInstructions - Copy.txt.old" />
    <None Remove="DavidTurner_Resume.docx" />
    <None Remove="PortraitServices\LivePortrait\pretrained_weights\liveportrait_animals\base_models\appearance_feature_extractor.pth" />
    <None Remove="PortraitServices\LivePortrait\pretrained_weights\liveportrait_animals\base_models\motion_extractor.pth" />
    <None Remove="PortraitServices\LivePortrait\pretrained_weights\liveportrait_animals\base_models\spade_generator.pth" />
    <None Remove="PortraitServices\LivePortrait\pretrained_weights\liveportrait_animals\base_models\warping_module.pth" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />
    <PackageReference Include="NuGet.Packaging" Version="7.9.0" />
    <PackageReference Include="NuGet.Protocol" Version="7.9.0" />
    <ProjectReference Include="..\CorporatePortfolio.Client\CorporatePortfolio.Client.csproj" />
    <ProjectReference Include="..\CorporatePortfolio.Services\CorporatePortfolio.Services.csproj" />
    <PackageReference Include="Blazor.Bootstrap" Version="4.0.0" />
    <PackageReference Include="DocX" Version="5.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Facebook" Version="10.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="10.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.12" />
    <PackageReference Include="Microsoft.Identity.Web" Version="4.14.2" />
    <PackageReference Include="Microsoft.Identity.Web.UI" Version="4.14.2" />
    <PackageReference Include="MudBlazor" Version="9.10.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\DavidTurner_Resume.docx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="PortraitServices\LivePortrait\pretrained_weights\liveportrait_animals\base_models\" />
  </ItemGroup>

</Project>
